version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "monthly"
    groups:
      action-dependencies:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"